In [2]:
import pandas as pd
import numpy as np
import math

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
sns.set()

In [3]:
import sigma_equation as se

In [ ]:
#cecita, complessita, disistima_espressa, disistima_ricevuta, rifiuto_effettivo

In [21]:
tensore_equazione_sigma = np.zeros(shape = (10,10,10,10,10))
for cecita in range(0,10):
    for complessita in range(0,10):
        for disistima_espressa in range(0,10):
            for disistima_ricevuta in range(0,10):
                for rifiuto_effettivo in range(0,10):
                        tensore_equazione_sigma[cecita,complessita,disistima_espressa,disistima_ricevuta,rifiuto_effettivo] = se.sigma_equation(cecita/10,complessita/10,disistima_espressa/10,disistima_ricevuta/10,rifiuto_effettivo/10)

In [22]:
# generate a numpy arrays of numbers from 0 to 1 with step 0.1
x = np.arange(0, 1.1, 0.1)
y = np.arange(0, 1.1, 0.1)
x, y

(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

In [23]:
tensore_equazione_sigma[0,0,0,:,:].shape

(10, 10)

In [24]:
tensore_equazione_sigma[0,0,0,:,:]

array([[ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.]])

In [26]:
fig = go.Figure(data=[go.Surface(x = x, y = y, z=tensore_equazione_sigma[0,0,0,:,:])])
fig.update_layout(title='Sigma equation', autosize=False,
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90))
# change the labels of the axes
fig.update_xaxes(title_text='disistima_ricevuta')
fig.update_yaxes(title_text='rifiuto_effettivo')
#fig.update_zaxes(title_text='Sigma')
fig.show()